/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sinieco_mylive_pusher_PusherNative */

#ifndef _Included_com_sinieco_mylive_pusher_PushNative
#define _Included_com_sinieco_mylive_pusher_PushNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sinieco_mylive_pusher_PusherNative
 * Method:    startPush
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_sinieco_mylive_pusher_PushNative_startPush
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_sinieco_mylive_pusher_PusherNative
 * Method:    stopPush
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sinieco_mylive_pusher_PushNative_stopPush
  (JNIEnv *, jobject);

/*
 * Class:     com_sinieco_mylive_pusher_PusherNative
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sinieco_mylive_pusher_PushNative_release
  (JNIEnv *, jobject);

/*
 * Class:     com_sinieco_mylive_pusher_PusherNative
 * Method:    setViedeoOptions
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_sinieco_mylive_pusher_PushNative_setViedeoOptions
  (JNIEnv *, jobject, jint, jint, jint ,jint);

/*
 * Class:     com_sinieco_mylive_pusher_PusherNative
 * Method:    setAudioOptions
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_sinieco_mylive_pusher_PushNative_setAudioOptions
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_sinieco_mylive_pusher_PusherNative
 * Method:    fireViedo
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_sinieco_mylive_pusher_PushNative_fireViedo
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_sinieco_mylive_pusher_PusherNative
 * Method:    fireAudio
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_sinieco_mylive_pusher_PushNative_fireAudio
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
